version: 2
updates:
  # Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "go"
    ignore:
      # メジャーバージョンアップは手動で対応
      - dependency-name: "github.com/gin-gonic/gin"
        update-types: ["version-update:semver-major"]
      - dependency-name: "github.com/lib/pq"
        update-types: ["version-update:semver-major"]
      - dependency-name: "github.com/google/uuid"
        update-types: ["version-update:semver-major"]
      - dependency-name: "github.com/joho/godotenv"
        update-types: ["version-update:semver-major"]
      - dependency-name: "github.com/stretchr/testify"
        update-types: ["version-update:semver-major"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"

  # Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
    ignore:
      # メジャーバージョンアップは手動で対応
      - dependency-name: "golang"
        update-types: ["version-update:semver-major"]
      - dependency-name: "alpine"
        update-types: ["version-update:semver-major"]
      - dependency-name: "postgres"
        update-types: ["version-update:semver-major"] 