version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: iot-platform-postgres
    environment:
      POSTGRES_DB: iot_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - iot-network

  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: iot-platform-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./configs/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
      - mosquitto_logs:/mosquitto/log
    networks:
      - iot-network

  # Optional: Grafana for data visualization
  grafana:
    image: grafana/grafana:latest
    container_name: iot-platform-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - iot-network
    depends_on:
      - postgres

volumes:
  postgres_data:
  mosquitto_data:
  mosquitto_logs:
  grafana_data:

networks:
  iot-network:
    driver: bridge 